services:
    deploy:
        image: tomcat:9.0.111-jre21-temurin-jammy
        ports:
            - '8080:8080'
        volumes:
            - app:/usr/local/tomcat/webapps
        depends_on:
            - builder
            - db
    builder:
        build:
            context: .
        volumes:
           - app:/root/homework12/App42PaaS-Java-MySQL-Sample/target

    db:
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: homework12
            MYSQL_USER: user
            MYSQL_PASSWORD: password123

volumes:
    app:
    data: